package com.qualizeal;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.stream.Stream;

import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.condition.DisabledIf;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

@TestInstance(Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
public class AppTest {
	static Class<?> operationClass;
	static Method operationMethod;
	static int counter1forTest3, counter1forTest4, counter1forTest5;
	static int counter2forTest3, counter2forTest4, counter2forTest5;
	static int counter3forTest3, counter3forTest4, counter3forTest5;

	@Test
	@Order(1)
	public void test1() {
		boolean isValidPackageAndClassName = true;
				
		try {
			operationClass = Class.forName("com.qualizeal.javaapp05.operation.EvenOddNumber");
		} catch (ClassNotFoundException cnfEx) {
			isValidPackageAndClassName = false;
		} catch (NoClassDefFoundError ncdfErr) {
			isValidPackageAndClassName = false;
		}
		
		assertTrue(isValidPackageAndClassName, "Either the package name or class name does not match with the guideline.");
	}

	boolean customConditionForClass() {
		return (operationClass == null) ? true : false;
	}

	@Test
	@Order(2)
	@DisabledIf("customConditionForClass")
	public void test2() {
		boolean isValidMethod = true;
		
		try {
			operationMethod = operationClass.getMethod("verifyIfNumberIsEvenOrOdd", Integer.TYPE);
			
			String expectedMethodSyntax = "public java.lang.String com.qualizeal.javaapp05.operation.EvenOddNumber.verifyIfNumberIsEvenOrOdd(int)";
			String actualMethodSyntax = operationMethod.toString();
			
			if (!actualMethodSyntax.equals(expectedMethodSyntax)) {
				isValidMethod = false;
			}
		} catch (NoSuchMethodException nsmEx) {
			isValidMethod = false;
		}
		
		assertTrue(isValidMethod, "The method name or syntax does not match with the guideline.");
	}

	boolean customConditionForMethod() {
		return (operationMethod == null) ? true : false;
	}

	static Stream<Arguments> numbersProviderForTest3() {
		return Stream.of(
					Arguments.of(10),
					Arguments.of(9)
				);
	}

	@ParameterizedTest
	@MethodSource({"numbersProviderForTest3"})
	@Order(3)
	@DisabledIf("customConditionForMethod")
	public void test3(int num) {
		int[] sampleInputs = {1, 2};
		int[] parameters1 = {10, 9};
		String[] expectedResults = {"Even Number", "Odd Number"};
		
		try {
			Object classObject = operationClass.getDeclaredConstructor((Class<?>[]) new Class[0]).newInstance(new Object[0]);
			
			String actualResult = (String) operationMethod.invoke(classObject, num);
			
			assertEquals(expectedResults[counter1forTest3++], actualResult, "The result generated by the method does not match with the Expected Output of Sample Input " + sampleInputs[counter2forTest3++] + ": " + parameters1[counter3forTest3++]);
		} catch (InstantiationException | IllegalAccessException | InvocationTargetException | NoSuchMethodException ex) {
		}
	}

	static Stream<Arguments> numbersProviderForTest4() {
		return Stream.of(
					Arguments.of(-10)
				);
	}

	@ParameterizedTest
	@MethodSource({"numbersProviderForTest4"})
	@Order(4)
	@DisabledIf("customConditionForMethod")
	public void test4(int num) {
		int[] sampleInputs = {3};
		int[] parameters1 = {-10};
		String[] expectedResults = {"-1"};
		
		try {
			Object classObject = operationClass.getDeclaredConstructor((Class<?>[]) new Class[0]).newInstance(new Object[0]);
			
			String actualResult = (String) operationMethod.invoke(classObject, num);
			
			assertEquals(expectedResults[counter1forTest4++], actualResult, "The result generated by the method does not match with the Expected Output of Sample Input " + sampleInputs[counter2forTest4++] + ": " + parameters1[counter3forTest4++]);
		} catch (InstantiationException | IllegalAccessException | InvocationTargetException | NoSuchMethodException ex) {
		}
	}

	static Stream<Arguments> numbersProviderForTest5() {
		return Stream.of(
				Arguments.of(0)
			);
	}

	@ParameterizedTest
	@MethodSource({"numbersProviderForTest5"})
	@Order(5)
	@DisabledIf("customConditionForMethod")
	public void test5(int num) {
		int[] sampleInputs = {4};
		int[] parameters1 = {0};
		String[] expectedResults = {"-2"};
		
		try {
			Object classObject = operationClass.getDeclaredConstructor((Class<?>[]) new Class[0]).newInstance(new Object[0]);
			
			String actualResult = (String) operationMethod.invoke(classObject, num);
			
			assertEquals(expectedResults[counter1forTest5++], actualResult, "The result generated by the method does not match with the Expected Output of Sample Input " + sampleInputs[counter2forTest5++] + ": " + parameters1[counter3forTest5++]);
		} catch (InstantiationException | IllegalAccessException | InvocationTargetException | NoSuchMethodException ex) {
		}
	}
}